# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: .NET

on:
  push:
    #branches: [ "disabled" ]
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
    #branches: [ "disabled" ]

jobs:
  build-and-release:
    runs-on: windows-latest
    steps:
      # Step 1: Checkout code
      - uses: actions/checkout@v2

      # Step 2: Setup .NET (use the appropriate version for your project)
      - name: Setup .NET
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '6.0'  # Use the version that matches your project
      
      # Step 3: Install dotnet-script tool (if not installed already)
      - name: Install dotnet-script tool
        run: dotnet tool install --global dotnet-script

      # Step 4: Generate version info using the build.csx script
      - name: Generate version
        run: |
          dotnet script ./TS3AudioBot/build.csx TS3AudioBot/obj/Debug/net6.0/Version.g.cs $(BuildConfiguration)

      - name: Restore dependencies
        run: dotnet restore

      - name: Test
        run: dotnet test --no-build --verbosity normal

      # Step 5: Run tests
      - name: Build
        run: dotnet build --no-restore

      # Step 8: Extract version from the generated file (Version.g.cs)
      - name: Extract version from file
        id: extract_version
        run: |
          VERSION=$(grep -oP '(?<=this.Version = ")[^"]*' TS3AudioBot/obj/Debug/net6.0/Version.g.cs)
          echo "VERSION=${VERSION}" >> $GITHUB_ENV


      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.TOKEN }}
        with:
          tag_name: ${{ env.VERSION }}
          release_name: "Release ${{ env.VERSION }}" # set the release name here
          body: |
            This is the release notes for version ${{ env.VERSION }}
          draft: false
          prerelease: false
