# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: .NET

on:
  push:
    #branches: [ "disabled" ]
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
    #branches: [ "disabled" ]

jobs:
  build-and-release:
    runs-on: windows-latest
    steps:
      # Step 1: Checkout code
      - uses: actions/checkout@v2

      # Step 2: Setup .NET (use the appropriate version for your project)
      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '6.0.x'
      
      # Step 3: Install a compatible dotnet-script tool (version 1.0.0 is compatible with .NET 6.0) D:\a\KBTS3AudioBot\KBTS3AudioBot\TS3AudioBot
      - name: Install dotnet-script tool (version 1.5.0)
        run: dotnet tool install --global dotnet-script --version 1.5.0

      - name: Build Project
        run: dotnet build --configuration Debug

      - name: Generate version
        run: |
          # Run the script to generate the version and capture the output
          $version = dotnet script ./TS3AudioBot/build.csx TS3AudioBot/obj/Debug/net6.0/Version.g.cs ${{ env.BuildConfiguration }}
          # Set the VERSION environment variable in GitHub Actions
          echo "VERSION=$version" >> $GITHUB_ENV
        env:
          BuildConfiguration: Debug

      - name: Restore dependencies
        run: dotnet restore

      - name: Test
        run: dotnet test --no-build --verbosity normal

      # Step 5: Run tests
      - name: Build
        run: dotnet build --no-restore

      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.TOKEN }}
        with:
          tag_name: ${{ env.VERSION }}
          release_name: "Release ${{ env.VERSION }}" # set the release name here
          body: |
            This is the release notes for version ${{ env.VERSION }}
          draft: false
          prerelease: false
